---
server:
    install: '1'
    packages: [git]
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: accelerato, ip: 192.168.33.99, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
mysql:
    install: '1'
    root_password: '123'
    database: db
    user: accelerato
    password: secret
    dump: ''

